# Generated by Django 5.2.7 on 2025-11-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mockquestion_sample_answer'),
        ('accounts', '0007_mockquestion_media_file_speakingsubmission_and_more'),
    ]

    operations = [
    ]
