# Generated by Django 5.2.7 on 2025-11-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_mockquestion_sample_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockquestion',
            name='sample_answer',
            field=models.TextField(blank=True, help_text='Sample answer text for speaking questions', null=True),
        ),
    ]
