# Generated by Django 5.2.7 on 2025-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mockquestion_sample_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='auto_weight',
            field=models.FloatField(default=0.7, help_text='Trọng số chấm tự động (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='manual_weight',
            field=models.FloatField(default=0.3, help_text='Trọng số chấm tay (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='speech_language',
            field=models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('en-AU', 'English (Australia)')], default='en-US', help_text='Ngôn ngữ sử dụng cho nhận dạng giọng nói', max_length=10),
        ),
    ]
