# Generated by Django 5.2.7 on 2025-11-12 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mockexam_auto_weight_mockexam_manual_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=320)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
            ],
            options={
                'verbose_name': 'Sent Email',
                'verbose_name_plural': 'Sent Emails',
            },
        ),
    ]
